In [4]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
import seaborn as sns
import matplotlib.pyplot as plt

/kaggle/input/tweezer/tweetsterror.xlsx
/kaggle/input/tweezer/randomtweets.xlsx


Importing the datasets

In [5]:
data1 = pd.read_excel('/kaggle/input/tweezer/tweetsterror.xlsx')
data2 = pd.read_excel('/kaggle/input/tweezer/randomtweets.xlsx')

In [6]:
data1.head()

name         username  \
0  GunsandCoffee  GunsandCoffee70   
1  GunsandCoffee  GunsandCoffee70   
2  GunsandCoffee  GunsandCoffee70   
3  GunsandCoffee  GunsandCoffee70   
4  GunsandCoffee  GunsandCoffee70   

                                    description location  followers  \
0  ENGLISH TRANSLATIONS: http://t.co/QLdJ0ftews      NaN        640   
1  ENGLISH TRANSLATIONS: http://t.co/QLdJ0ftews      NaN        640   
2  ENGLISH TRANSLATIONS: http://t.co/QLdJ0ftews      NaN        640   
3  ENGLISH TRANSLATIONS: http://t.co/QLdJ0ftews      NaN        640   
4  ENGLISH TRANSLATIONS: http://t.co/QLdJ0ftews      NaN        640   

   numberstatuses                 time  \
0              49  2015-06-01 21:07:00   
1              49       1/6/2015 21:27   
2              49       1/6/2015 21:29   
3              49       1/6/2015 21:37   
4              49       1/6/2015 21:45   

                                              tweets  
0  ENGLISH TRANSLATION: 'A MESSAGE TO THE TRUTHFU...  
1  ENGLISH TRANSLATION: SHEIKH FATIH AL JAWLANI '...  
2  ENGLISH TRANSLATION: FIRST AUDIO MEETING WITH ...  
3  ENGLISH TRANSLATION: SHEIKH NASIR AL WUHAYSHI ...  
4  ENGLISH TRANSLATION: AQAP: 'RESPONSE TO SHEIKH...

In [7]:
data2.head()

Tweet Id        Date   Hour         User Name       Nickname  \
0  721318437075685382  2016-04-16  12:44    Bill Schulhoff  BillSchulhoff   
1  721318436173979648  2016-04-16  12:44     Daniele Polis      danipolis   
2  721318434169102336  2016-04-16  12:44      Kasey Jacobs      KJacobs27   
3  721318429844582400  2016-04-16  12:44       Stan Curtis      stncurtis   
4  721318429081407488  2016-04-16  12:44  Dave Borzymowski       wi_borzo   

                                                 Bio  \
0  Husband,Dad,GrandDad,Ordained Minister, Umpire...   
1  Viagens, geek, moda, batons laranja, cabelos c...   
2                   Norwich University Class of 2017   
3  transcendental music, art for art's sake, craf...   
4                            When in doubt....Panic.   

                                       Tweet content  Favs  RTs   Latitude  \
0  Wind 3.2 mph NNE. Barometer 30.20 in, Rising s...   NaN  NaN  40.760278   
1  Pausa pro café antes de embarcar no próximo vô...   NaN  NaN  32.898349   
2  Good. Morning. #morning #Saturday #diner #VT #...   NaN  NaN  44.199476   
3  @gratefuldead recordstoredayus 🌹🌹🌹 @ TOMS MUSI...   NaN  NaN  39.901474   
4  Egg in a muffin!!! (@ Rocket Baby Bakery - @ro...   NaN  NaN  43.060849   

   Longitude Country Place (as appears on Bio)  \
0 -72.954722      US        East Patchogue, NY   
1 -97.039196      US             Grapevine, TX   
2 -72.504173      US                 Barre, VT   
3 -76.606817      US              Red Lion, PA   
4 -87.998309      US             Wauwatosa, WI   

                                     Profile picture  Followers  Following  \
0  http://pbs.twimg.com/profile_images/3788000007...      386.0      705.0   
1  http://pbs.twimg.com/profile_images/7041760340...      812.0      647.0   
2  http://pbs.twimg.com/profile_images/7169585649...      179.0      206.0   
3  http://pbs.twimg.com/profile_images/6962528246...     1229.0     2071.0   
4  http://pbs.twimg.com/profile_images/6595279129...      129.0      833.0   

   Listed Tweet language (ISO 639-1)  \
0    24.0                         en   
1    16.0                         pt   
2     2.0                         en   
3    11.0                         en   
4     9.0                         en   

                                           Tweet Url  
0  http://www.twitter.com/BillSchulhoff/status/72...  
1  http://www.twitter.com/danipolis/status/721318...  
2  http://www.twitter.com/KJacobs27/status/721318...  
3  http://www.twitter.com/stncurtis/status/721318...  
4  http://www.twitter.com/wi_borzo/status/7213184...

In [21]:
data2['Tweet language (ISO 639-1)'].value_counts()

en    172206
es     27062
fr      1695
it       959
pt       737
de       636
da       442
nl       282
ru       277
sv       271
fi       125
tr        91
hu        37
Name: Tweet language (ISO 639-1), dtype: int64

Since tweets also contain non-english tweets therefore we will remove them.

In [31]:
data1_tweets = data1[['tweets']]
data1_tweets['label'] = 1
# label 1 for tweets related to terrorists or their sympathisers

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [32]:
data2_temp = data2[data2['Tweet language (ISO 639-1)']=='en']
data2_tweets = data2_temp[['Tweet content']]
data2_tweets['label'] = 0
# label 0 for tweets related to non-(terrorists or their sympathisers)

/opt/conda/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [39]:
data2_tweets.rename(columns  = {"Tweet content": "tweets"}, 
                                 inplace = True) 

In [40]:
data1_tweets.head()

tweets  label
0  ENGLISH TRANSLATION: 'A MESSAGE TO THE TRUTHFU...      1
1  ENGLISH TRANSLATION: SHEIKH FATIH AL JAWLANI '...      1
2  ENGLISH TRANSLATION: FIRST AUDIO MEETING WITH ...      1
3  ENGLISH TRANSLATION: SHEIKH NASIR AL WUHAYSHI ...      1
4  ENGLISH TRANSLATION: AQAP: 'RESPONSE TO SHEIKH...      1

In [41]:
data2_tweets.head()

tweets  label
0  Wind 3.2 mph NNE. Barometer 30.20 in, Rising s...      0
2  Good. Morning. #morning #Saturday #diner #VT #...      0
3  @gratefuldead recordstoredayus 🌹🌹🌹 @ TOMS MUSI...      0
4  Egg in a muffin!!! (@ Rocket Baby Bakery - @ro...      0
5  @lyricwaters should've gave the neighbor  a bu...      0

In [42]:
data1_tweets.shape

(17410, 2)

In [43]:
data2_tweets.shape

(172206, 2)

Concatenating both datasets for furthur processing

In [49]:
dataset = pd.concat([data1_tweets, data2_tweets])

In [50]:
dataset.head()

tweets  label
0  ENGLISH TRANSLATION: 'A MESSAGE TO THE TRUTHFU...      1
1  ENGLISH TRANSLATION: SHEIKH FATIH AL JAWLANI '...      1
2  ENGLISH TRANSLATION: FIRST AUDIO MEETING WITH ...      1
3  ENGLISH TRANSLATION: SHEIKH NASIR AL WUHAYSHI ...      1
4  ENGLISH TRANSLATION: AQAP: 'RESPONSE TO SHEIKH...      1

Let's now divide dataset into train and test datasets

In [51]:
from sklearn.model_selection import train_test_split

In [55]:
X_train, X_test, y_train, y_test = train_test_split(dataset['tweets'],
                                                    dataset['label'], test_size=0.25, random_state=42)

Importing necessary functionalities

In [77]:
from sklearn.feature_extraction.text import TfidfTransformer ,CountVectorizer

In [59]:
from sklearn.naive_bayes import MultinomialNB

In [60]:
from sklearn.pipeline import Pipeline

In [61]:
from sklearn.neighbors import KNeighborsClassifier

In [70]:
import re
import string
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [81]:
from sklearn.metrics import classification_report, confusion_matrix

In [64]:
from nltk.corpus import stopwords

function for pre-processing

In [73]:
def lemmatizer_preprocessing(mess):
    nopunc = [char for char in mess if char not in string.punctuation]
    nopunc = ''.join(nopunc)
    nopunc = [lemmatizer.lemmatize(word) for word in nopunc.split()]
    nopunc = [word for word in nopunc if word.lower() not in stopwords.words('english')]
    temp =  ' '.join(nopunc).strip()
    return re.sub(r'[^\w]', ' ', temp)

In [78]:
pipeline1 = Pipeline([
    ('bow', CountVectorizer(analyzer=lemmatizer_preprocessing)),
    ('classifier', MultinomialNB()),
    #('classifier',KNeighborsClassifier(n_neighbors=2)),
])

In [79]:
pipeline1.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('bow',
                 CountVectorizer(analyzer=<function lemmatizer_preprocessing at 0x7fde65a76c80>,
                                 binary=False, decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('classifier',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [80]:
prediction1 = pipeline1.predict(X_test)

In [82]:
print(confusion_matrix(prediction1,y_test))
print(classification_report(prediction1,y_test))

[[42838  2750]
 [  254  1562]]
              precision    recall  f1-score   support

           0       0.99      0.94      0.97     45588
           1       0.36      0.86      0.51      1816

    accuracy                           0.94     47404
   macro avg       0.68      0.90      0.74     47404
weighted avg       0.97      0.94      0.95     47404



In [83]:
pipeline2 = Pipeline([
    ('bow', CountVectorizer(analyzer=lemmatizer_preprocessing)),
    #('classifier', MultinomialNB()),
    ('classifier',KNeighborsClassifier(n_neighbors=2)),
])

In [84]:
pipeline2.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('bow',
                 CountVectorizer(analyzer=<function lemmatizer_preprocessing at 0x7fde65a76c80>,
                                 binary=False, decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('classifier',
                 KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                      metric='minkowski', metric_params=None,
                                      n_jobs=None, n_neighbors=2, p=2,
                                      w

In [85]:
prediction2 = pipeline2.predict(X_test)

In [86]:
print(confusion_matrix(prediction2,y_test))
print(classification_report(prediction2,y_test))

[[42817  2557]
 [  275  1755]]
              precision    recall  f1-score   support

           0       0.99      0.94      0.97     45374
           1       0.41      0.86      0.55      2030

    accuracy                           0.94     47404
   macro avg       0.70      0.90      0.76     47404
weighted avg       0.97      0.94      0.95     47404



In [98]:
pipeline1.predict_proba(['jihad sheikh'])

array([[0.7976114, 0.2023886]])

In [101]:
from sklearn.externals import joblib

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
joblib.dump(pipeline1, 'filename.pkl')